/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

import com.sun.awt.AWTUtilities;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author orlando
 */
public class Add_letra extends javax.swing.JFrame {

    /**
     * Creates new form Add_letra
     */
    PepperMusic_Frame ventana;
    public Add_letra(PepperMusic_Frame ventana) {
        this.ventana = ventana;
        this.setUndecorated(true);
          initComponents();
       this.setSize(new Dimension(300, 336));
          this.setMinimumSize(new Dimension(0, 0));
          this.setLocationRelativeTo(null);
          this.setResizable(false); // anula el boton maximizar
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,125,125);
        AWTUtilities.setWindowShape(this, forma);
        
         if(ventana.jp_Principal.getComponent(2)==ventana.inicio.p1)leer_txt("C:\\PepperMusic_Datos\\Letras\\"+ventana.lista_completa.get(ventana.indice).nom_cancion+".txt");
             if(ventana.jp_Principal.getComponent(2)==ventana.inicio.p2)leer_txt("C:\\PepperMusic_Datos\\Letras\\"+ventana.Lista_album.get(ventana.indice_album).items_album().get(ventana.indice_cancion).nom_cancion+".txt");
            if(ventana.jp_Principal.getComponent(2)==ventana.inicio.p3)leer_txt("C:\\PepperMusic_Datos\\Letras\\"+ventana.Lista_artista.get(ventana.indice_album).items_artista().get(ventana.indice_cancion).nom_cancion+".txt");
             if(ventana.jp_Principal.getComponent(2)==ventana.inicio.p4)leer_txt("C:\\PepperMusic_Datos\\Letras\\"+ventana.Lista_genero.get(ventana.indice_album).items_genero().get(ventana.indice_cancion).nom_cancion+".txt");
        jlb_nombre.setText(ventana.nom_cancion);
    }
 public void leer_txt(String ruta){
     
     String codigo = new String(), path = ruta;
			File archivo = new File(path);
     if (archivo.exists()){
			FileReader fr = null;
			BufferedReader entrada = null;
			try {
				fr = new FileReader(path);
				entrada = new BufferedReader(fr);

				while(entrada.ready()){
					codigo += entrada.readLine()+"\n";
				}

			}catch(IOException e) {
				e.printStackTrace();
			}finally{
				try{                    
					if(null != fr){   
						fr.close();     
					}                  
				}catch (Exception e2){ 
					e2.printStackTrace();
				}
			}
            
     }
                      jtxt_letra.setText(codigo);
                      StyledDocument doc = jtxt_letra.getStyledDocument();
                       SimpleAttributeSet center = new SimpleAttributeSet();
                      StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
                       doc.setParagraphAttributes(0, doc.getLength(), center, false);
                      
 }
    
    private Add_letra() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxt_letra = new javax.swing.JTextPane();
        jlb_nombre = new javax.swing.JLabel();
        jb_Cerrar = new javax.swing.JButton();
        jb_Minimizar = new javax.swing.JButton();
        jb_setear = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_listo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jtxt_letra.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(jtxt_letra);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(28, 45, 220, 260);

        jlb_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlb_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_nombre.setText("jlb_nombre");
        getContentPane().add(jlb_nombre);
        jlb_nombre.setBounds(60, 20, 140, 20);

        jb_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        jb_Cerrar.setAlignmentY(0.0F);
        jb_Cerrar.setBorder(null);
        jb_Cerrar.setBorderPainted(false);
        jb_Cerrar.setContentAreaFilled(false);
        jb_Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_Cerrar.setIconTextGap(-3);
        jb_Cerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jb_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar3.png"))); // NOI18N
        jb_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Cerrar);
        jb_Cerrar.setBounds(230, 0, 30, 30);

        jb_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_minimizar.png"))); // NOI18N
        jb_Minimizar.setBorder(null);
        jb_Minimizar.setBorderPainted(false);
        jb_Minimizar.setContentAreaFilled(false);
        jb_Minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_minimizar2.png"))); // NOI18N
        jb_Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Minimizar);
        jb_Minimizar.setBounds(193, 0, 30, 30);

        jb_setear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/letra_setear.png"))); // NOI18N
        jb_setear.setBorder(null);
        jb_setear.setBorderPainted(false);
        jb_setear.setContentAreaFilled(false);
        jb_setear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/letra_setear2.png"))); // NOI18N
        jb_setear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_setearActionPerformed(evt);
            }
        });
        getContentPane().add(jb_setear);
        jb_setear.setBounds(250, 50, 30, 30);

        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/letra_eliminar.png"))); // NOI18N
        jb_eliminar.setBorder(null);
        jb_eliminar.setBorderPainted(false);
        jb_eliminar.setContentAreaFilled(false);
        jb_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/letra_eliminar2.png"))); // NOI18N
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_eliminar);
        jb_eliminar.setBounds(250, 90, 30, 30);

        jb_listo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/letra_listo.png"))); // NOI18N
        jb_listo.setBorder(null);
        jb_listo.setBorderPainted(false);
        jb_listo.setContentAreaFilled(false);
        jb_listo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_listo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/letra_listo2.png"))); // NOI18N
        jb_listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_listo);
        jb_listo.setBounds(250, 130, 30, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Celeste.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x, y;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        Point p = MouseInfo.getPointerInfo().getLocation();
          this.setLocation(p.x-x,p.y-y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jb_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CerrarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jb_CerrarActionPerformed

    private void jb_MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MinimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jb_MinimizarActionPerformed

    private void jb_listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listoActionPerformed
        try {
            // TODO add your handling code here:
           if(!jtxt_letra.getText().isEmpty()){
              //  BufferedWriter bw = new BufferedWriter(new File("C:\\PepperMusic_Datos\\Letras\\"+ventana.lista_completa.get(ventana.indice).nom_cancion+".txt"));
               
           FileWriter guardar = new FileWriter(new File("C:\\PepperMusic_Datos\\Letras\\"+ventana.lista_completa.get(ventana.indice).nom_cancion+".txt"));
          
           jtxt_letra.write(guardar);
           JOptionPane.showMessageDialog(this,"Se ha guardado exitosamente la letra de "+ventana.nom_cancion+" \nen el cancionero" ,"PepperMusic:Guardado Exitoso!",JOptionPane.INFORMATION_MESSAGE);
            guardar.close();
            ventana.repro.leer_txt("C:\\PepperMusic_Datos\\Letras\\"+ventana.lista_completa.get(ventana.indice).nom_cancion+".txt");
            ventana.repro.js_Letras.getVerticalScrollBar().setValue(0);
            this.dispose();
           }else{
               JOptionPane.showMessageDialog(this,"No se ha detectado texto alguno. Escriba algo" ,"PepperMusic:Sin Texto",JOptionPane.ERROR_MESSAGE);
               System.out.println("vacio");
           }
        } catch (IOException ex) {
            Logger.getLogger(Add_letra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_listoActionPerformed

    private void jb_setearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_setearActionPerformed
        // TODO add your handling code here:
        jtxt_letra.setText("");
        
        
    }//GEN-LAST:event_jb_setearActionPerformed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        // TODO add your handling code here:
        File eliminar = new File("C:\\PepperMusic_Datos\\Letras\\"+ventana.lista_completa.get(ventana.indice).nom_cancion+".txt");
        if(eliminar.exists()){
            eliminar.delete();
            JOptionPane.showMessageDialog(this,"Se ha eliminando existosamente la letra de esta canción" ,"PepperMusic:Borrado Exitoso!",JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Archivo no existente. Imposible borrar" ,"PepperMusic:Eliminar",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jb_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_letra( ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Cerrar;
    private javax.swing.JButton jb_Minimizar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_listo;
    private javax.swing.JButton jb_setear;
    private javax.swing.JLabel jlb_nombre;
    private javax.swing.JTextPane jtxt_letra;
    // End of variables declaration//GEN-END:variables
}
