/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

import static java.awt.Frame.ICONIFIED;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author orlando
 */
public class jp_Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form jp_Configuracion
     */
    PepperMusic_Frame ventana;
    public jp_Configuracion(PepperMusic_Frame venta) {
        
        initComponents();
        ventana=venta;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_Regresar = new javax.swing.JButton();
        jb_Minimizar = new javax.swing.JButton();
        jb_Cerrar = new javax.swing.JButton();

        setLayout(null);

        jb_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_regresar.png"))); // NOI18N
        jb_Regresar.setBorder(null);
        jb_Regresar.setBorderPainted(false);
        jb_Regresar.setContentAreaFilled(false);
        jb_Regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_regresar2.png"))); // NOI18N
        jb_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_RegresarActionPerformed(evt);
            }
        });
        add(jb_Regresar);
        jb_Regresar.setBounds(90, 302, 123, 30);

        jb_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_minimizar.png"))); // NOI18N
        jb_Minimizar.setBorder(null);
        jb_Minimizar.setBorderPainted(false);
        jb_Minimizar.setContentAreaFilled(false);
        jb_Minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_minimizar2.png"))); // NOI18N
        jb_Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MinimizarActionPerformed(evt);
            }
        });
        add(jb_Minimizar);
        jb_Minimizar.setBounds(193, 0, 30, 30);

        jb_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        jb_Cerrar.setAlignmentY(0.0F);
        jb_Cerrar.setBorder(null);
        jb_Cerrar.setBorderPainted(false);
        jb_Cerrar.setContentAreaFilled(false);
        jb_Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_Cerrar.setIconTextGap(-3);
        jb_Cerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jb_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar3.png"))); // NOI18N
        jb_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CerrarActionPerformed(evt);
            }
        });
        add(jb_Cerrar);
        jb_Cerrar.setBounds(230, 0, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_RegresarActionPerformed
        // TODO add your handling code here:
       ventana.jp_Principal.getComponent(2).setVisible(false);
         ventana.jp_Principal.getComponent(1).setVisible(false);
         ventana.jp_Principal.getComponent(0).setVisible(true);

    }//GEN-LAST:event_jb_RegresarActionPerformed

    private void jb_MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MinimizarActionPerformed
        // TODO add your handling code here:
        ventana.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jb_MinimizarActionPerformed

    private void jb_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CerrarActionPerformed
        // TODO add your handling code here:
        if(ventana.EnRepro==true){ try {
           ventana.mi_reproductor.Stop();
           
           } catch (Exception ex) {
               Logger.getLogger(jp_Canciones.class.getName()).log(Level.SEVERE, null, ex);
               
           }}
        ventana.dispose();
    }//GEN-LAST:event_jb_CerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Cerrar;
    private javax.swing.JButton jb_Minimizar;
    private javax.swing.JButton jb_Regresar;
    // End of variables declaration//GEN-END:variables
}
