/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author orlando
 */
public class jp_Configuracion_Total extends jp_Configuracion {

    /**
     * Creates new form jp_Configuracion_Total
     */
    PepperMusic_Frame ventana;
    int frente=1;
    public jp_Configuracion_Total(PepperMusic_Frame venta) {
        super(venta);
       
       
        initComponents();
         ventana = venta;
         
          if(ventana.frente==0)jb_frente.setSelected(true);
        if(ventana.frente==1)jb_frente.setSelected(false);
         if (ventana.skin == 0){
             rd_predeterminado.setSelected(true);
              lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/fondo_principal4.png")));
              fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/Fondo_Celeste.png")));
         }
          if (ventana.skin == 1){
              rd_clasico.setSelected(true);
               lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/clasica4.png")));
               fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/clasica2.png")));
          }
           if (ventana.skin == 2){
               rd_rock.setSelected(true);
                lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/rock4.png")));
                  fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/rock2.png")));
           }
            if (ventana.skin == 3){
                rd_urbano.setSelected(true);
                lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/urbano4.png")));
                 fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/urbano2.png")));
            }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jb_frente = new javax.swing.JToggleButton();
        lb_previa = new javax.swing.JLabel();
        cmbIdiomas = new javax.swing.JComboBox();
        rd_predeterminado = new javax.swing.JRadioButton();
        rd_clasico = new javax.swing.JRadioButton();
        rd_rock = new javax.swing.JRadioButton();
        rd_urbano = new javax.swing.JRadioButton();
        jb_guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setLayout(null);

        jb_frente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/jtb_on.png"))); // NOI18N
        jb_frente.setBorder(null);
        jb_frente.setBorderPainted(false);
        jb_frente.setContentAreaFilled(false);
        jb_frente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/jtb_off.png"))); // NOI18N
        jb_frente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_frenteActionPerformed(evt);
            }
        });
        add(jb_frente);
        jb_frente.setBounds(200, 50, 50, 52);

        lb_previa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lb_previa);
        lb_previa.setBounds(130, 110, 143, 160);

        cmbIdiomas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Español", "Ingles", "Frances" }));
        cmbIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdiomasActionPerformed(evt);
            }
        });
        add(cmbIdiomas);
        cmbIdiomas.setBounds(60, 40, 90, 20);

        grupo1.add(rd_predeterminado);
        rd_predeterminado.setText("Moderno");
        rd_predeterminado.setOpaque(false);
        rd_predeterminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_predeterminadoActionPerformed(evt);
            }
        });
        add(rd_predeterminado);
        rd_predeterminado.setBounds(20, 110, 130, 23);

        grupo1.add(rd_clasico);
        rd_clasico.setText("Clásico");
        rd_clasico.setOpaque(false);
        rd_clasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_clasicoActionPerformed(evt);
            }
        });
        add(rd_clasico);
        rd_clasico.setBounds(20, 150, 130, 23);

        grupo1.add(rd_rock);
        rd_rock.setText("Rock");
        rd_rock.setOpaque(false);
        rd_rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_rockActionPerformed(evt);
            }
        });
        add(rd_rock);
        rd_rock.setBounds(20, 200, 130, 23);

        grupo1.add(rd_urbano);
        rd_urbano.setText("Urbano");
        rd_urbano.setOpaque(false);
        rd_urbano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_urbanoActionPerformed(evt);
            }
        });
        add(rd_urbano);
        rd_urbano.setBounds(20, 250, 130, 23);

        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });
        add(jb_guardar);
        jb_guardar.setBounds(160, 276, 90, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Siempre en frente:");
        jLabel2.setMaximumSize(new java.awt.Dimension(3000, 17));
        jLabel2.setName(""); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(60, 70, 130, 20);

        fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Celeste1.png"))); // NOI18N
        add(fondo1);
        fondo1.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_frenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_frenteActionPerformed
        // TODO add your handling code here:
       if(jb_frente.isSelected()) {
           ventana.setAlwaysOnTop(false);
           frente=0;
       }else{
           ventana.setAlwaysOnTop(true);
           frente=1;
       }
        
        //guardar esta configuracion
    }//GEN-LAST:event_jb_frenteActionPerformed

    private void rd_predeterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_predeterminadoActionPerformed
        // TODO add your handling code here:
        ventana.skin = 0;
        
        //ImageIcon icon = new ImageIcon(ventana.getClass().getResource("/Recursos/fondo_principal4.png"));
        lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/fondo_principal4.png")));
        
    }//GEN-LAST:event_rd_predeterminadoActionPerformed

    private void rd_clasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_clasicoActionPerformed
        // TODO add your handling code here:
        ventana.skin = 1;
         lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/clasica4.png")));
    }//GEN-LAST:event_rd_clasicoActionPerformed

    private void rd_rockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_rockActionPerformed
        // TODO add your handling code here:
        ventana.skin = 2;
         lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/rock4.png")));
    }//GEN-LAST:event_rd_rockActionPerformed

    private void rd_urbanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_urbanoActionPerformed
        // TODO add your handling code here:
        ventana.skin = 3;
         lb_previa.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/urbano4.png")));
    }//GEN-LAST:event_rd_urbanoActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
        FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("C:\\PepperMusic_Datos\\Configuracion\\Configuracion.txt");
            pw = new PrintWriter(fichero);
           
            
                pw.println(frente );
                  pw.println(ventana.skin );
                  pw.println(cmbIdiomas.getSelectedItem());
                  System.out.println(cmbIdiomas.getSelectedItem());
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           // Nuevamente aprovechamos el finally para 
           // asegurarnos que se cierra el fichero.
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
        ventana.Leer_config();
         JOptionPane.showMessageDialog(this,"Configuracion guardada, para notar los cambios \n Por favor reinicie el programa","PepperMusic:Configuracion Exitoso!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void cmbIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIdiomasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbIdiomas;
    private javax.swing.JLabel fondo1;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jb_frente;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JLabel lb_previa;
    private javax.swing.JRadioButton rd_clasico;
    private javax.swing.JRadioButton rd_predeterminado;
    private javax.swing.JRadioButton rd_rock;
    private javax.swing.JRadioButton rd_urbano;
    // End of variables declaration//GEN-END:variables
}
