/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

/**
 *
 * @author orlando
 */
public class jp_Configuracion_Generales extends jp_Configuracion {

    /**
     * Creates new form jp_Configuracion_Generales
     */
    PepperMusic_Frame ventana;
    public jp_Configuracion_Generales(PepperMusic_Frame venta) {
        super(venta);
        initComponents();
        ventana=venta;
        if(venta.isAlwaysOnTop()==true) jtb_top.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtb_top = new javax.swing.JToggleButton();
        btConfi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText(" Siempre visible");
        add(jLabel1);
        jLabel1.setBounds(60, 70, 100, 14);

        jtb_top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/jtb_on.png"))); // NOI18N
        jtb_top.setBorder(null);
        jtb_top.setBorderPainted(false);
        jtb_top.setContentAreaFilled(false);
        jtb_top.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/jtb_off.png"))); // NOI18N
        jtb_top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_topActionPerformed(evt);
            }
        });
        add(jtb_top);
        jtb_top.setBounds(170, 60, 50, 50);

        btConfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion.png"))); // NOI18N
        btConfi.setToolTipText("CONFIGURACIÓN");
        btConfi.setBorder(null);
        btConfi.setBorderPainted(false);
        btConfi.setContentAreaFilled(false);
        btConfi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConfi.setPreferredSize(new java.awt.Dimension(70, 70));
        btConfi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion3.png"))); // NOI18N
        btConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiActionPerformed(evt);
            }
        });
        add(btConfi);
        btConfi.setBounds(220, 250, 50, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Celeste1.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_topActionPerformed
        // TODO add your handling code here:
        if(jtb_top.isSelected()) ventana.setAlwaysOnTop(false);
        else ventana.setAlwaysOnTop(true);
    }//GEN-LAST:event_jtb_topActionPerformed

    private void btConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiActionPerformed
 ventana.jp_Principal.getComponent(2).setVisible(false);
        ventana.jp_Principal.remove(2);
            jp_Configuracion_Total p1 = new jp_Configuracion_Total(ventana);
            p1.setSize(300, 336);
            p1.setLocation(0, 0);
            p1.setVisible(true);
            ventana.jp_Principal.add(p1);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_btConfiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jtb_top;
    // End of variables declaration//GEN-END:variables
}
