/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

/**
 *
 * @author orlando
 */
public class jp_Configuracion_Total extends jp_Configuracion {

    /**
     * Creates new form jp_Configuracion_Total
     */
    PepperMusic_Frame ventana;
    public jp_Configuracion_Total(PepperMusic_Frame venta) {
        super(venta);
       
        initComponents();
         ventana = venta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_Configuracion_G = new javax.swing.JButton();
        jb_skins = new javax.swing.JButton();
        jb_ecua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jb_Configuracion_G.setText("GENERAL");
        jb_Configuracion_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Configuracion_GActionPerformed(evt);
            }
        });
        add(jb_Configuracion_G);
        jb_Configuracion_G.setBounds(73, 32, 143, 50);

        jb_skins.setText("SKINS");
        jb_skins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_skinsActionPerformed(evt);
            }
        });
        add(jb_skins);
        jb_skins.setBounds(73, 100, 140, 50);

        jb_ecua.setText("ECUALIZADOR");
        jb_ecua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ecuaActionPerformed(evt);
            }
        });
        add(jb_ecua);
        jb_ecua.setBounds(73, 177, 143, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Celeste1.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_skinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_skinsActionPerformed
        // TODO add your handling code here:
         ventana.jp_Principal.getComponent(2).setVisible(false); 
         ventana.jp_Principal.remove(2);
            jp_Configuracion_Skins p1 = new jp_Configuracion_Skins(ventana);
            p1.setSize(300, 336);
            p1.setLocation(0, 0);
            p1.setVisible(true);
            ventana.jp_Principal.add(p1);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_jb_skinsActionPerformed

    private void jb_Configuracion_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Configuracion_GActionPerformed
           ventana.jp_Principal.getComponent(2).setVisible(false);        // TODO add your handling code here:
        
            ventana.jp_Principal.remove(2);
            jp_Configuracion_Generales p1 = new jp_Configuracion_Generales(ventana);
            p1.setSize(300, 336);
            p1.setLocation(0, 0);
            p1.setVisible(true);
            ventana.jp_Principal.add(p1);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_jb_Configuracion_GActionPerformed

    private void jb_ecuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ecuaActionPerformed
        // TODO add your handling code here:
         ventana.jp_Principal.getComponent(2).setVisible(false); 
         ventana.jp_Principal.remove(2);
            jp_Ecualizador p1 = new jp_Ecualizador(ventana);
            p1.setSize(300, 336);
            p1.setLocation(0, 0);
            p1.setVisible(true);
            ventana.jp_Principal.add(p1);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_jb_ecuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_Configuracion_G;
    private javax.swing.JButton jb_ecua;
    private javax.swing.JButton jb_skins;
    // End of variables declaration//GEN-END:variables
}
