/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

/**
 *
 * @author orlando
 */
public class jp_Ecualizador extends jp_Configuracion {

    /**
     * Creates new form jp_Ecualizador
     */
    public jp_Ecualizador(PepperMusic_Frame venta) {
        super(venta);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider7 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btConfi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jSlider7.setMajorTickSpacing(20);
        jSlider7.setMaximum(10);
        jSlider7.setMinimum(-10);
        jSlider7.setMinorTickSpacing(5);
        jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider7.setPaintLabels(true);
        jSlider7.setPaintTicks(true);
        jSlider7.setSnapToTicks(true);
        jSlider7.setValue(0);
        jSlider7.setOpaque(false);
        add(jSlider7);
        jSlider7.setBounds(40, 40, 50, 200);

        jSlider6.setMajorTickSpacing(20);
        jSlider6.setMaximum(10);
        jSlider6.setMinimum(-10);
        jSlider6.setMinorTickSpacing(5);
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.setPaintLabels(true);
        jSlider6.setPaintTicks(true);
        jSlider6.setSnapToTicks(true);
        jSlider6.setValue(0);
        jSlider6.setOpaque(false);
        add(jSlider6);
        jSlider6.setBounds(110, 40, 50, 200);

        jSlider5.setMajorTickSpacing(20);
        jSlider5.setMaximum(10);
        jSlider5.setMinimum(-10);
        jSlider5.setMinorTickSpacing(5);
        jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider5.setPaintLabels(true);
        jSlider5.setPaintTicks(true);
        jSlider5.setSnapToTicks(true);
        jSlider5.setValue(0);
        jSlider5.setOpaque(false);
        add(jSlider5);
        jSlider5.setBounds(170, 40, 50, 200);

        jSlider4.setMajorTickSpacing(20);
        jSlider4.setMaximum(10);
        jSlider4.setMinimum(-10);
        jSlider4.setMinorTickSpacing(5);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setSnapToTicks(true);
        jSlider4.setValue(0);
        jSlider4.setOpaque(false);
        add(jSlider4);
        jSlider4.setBounds(230, 40, 50, 200);

        jLabel2.setText("GANANCIA");
        add(jLabel2);
        jLabel2.setBounds(220, 250, 70, 14);

        jLabel5.setText("GRAVES");
        add(jLabel5);
        jLabel5.setBounds(160, 250, 60, 14);

        jLabel4.setText("MEDIOS");
        add(jLabel4);
        jLabel4.setBounds(100, 250, 50, 14);

        jLabel3.setText("BAJOS");
        add(jLabel3);
        jLabel3.setBounds(40, 250, 40, 14);

        btConfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion.png"))); // NOI18N
        btConfi.setToolTipText("CONFIGURACIÓN");
        btConfi.setBorder(null);
        btConfi.setBorderPainted(false);
        btConfi.setContentAreaFilled(false);
        btConfi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConfi.setPreferredSize(new java.awt.Dimension(70, 70));
        btConfi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion3.png"))); // NOI18N
        btConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiActionPerformed(evt);
            }
        });
        add(btConfi);
        btConfi.setBounds(210, 270, 50, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Celeste1.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiActionPerformed
        ventana.jp_Principal.getComponent(2).setVisible(false);
        ventana.jp_Principal.remove(2);
        jp_Configuracion_Total p1 = new jp_Configuracion_Total(ventana);
        p1.setSize(300, 336);
        p1.setLocation(0, 0);
        p1.setVisible(true);
        ventana.jp_Principal.add(p1);
        ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_btConfiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    // End of variables declaration//GEN-END:variables
}
