/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

import static java.awt.Frame.ICONIFIED;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author orlando
 */
 
public class jp_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form jp_Inicio
     */
    int[] A={1,2,3};
    int indicador;
    PepperMusic_Frame ventana;
    public jp_Inicio(PepperMusic_Frame venta ) {
        initComponents();
        ventana = venta;
       
        p1= new jp_Lista(ventana);
        p2 = new jp_Lista_ALBUM(ventana);
        p3= new jp_Lista_ARTISTA(ventana);
          p4 = new jp_Lista_GENERO(ventana);
        p5 = new jp_Configuracion_Total(ventana);
       // if(A[1]==2)  System.out.println("hola"+A[1]);
       
       //imagen de fondo
       if (ventana.skin == 0){
            
              fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/fondo_principal.png")));
             
         }
          if (ventana.skin == 1){
             
               fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/clasica1.png")));
          }
           if (ventana.skin == 2){
              
                fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/rock1.png")));
           }
            if (ventana.skin == 3){
                
                fondo1.setIcon(new ImageIcon(ventana.getClass().getResource("/Recursos/urbano1.png")));
            }
            fondo1.revalidate();
            fondo1.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JOptionPane();
        btAlbum = new javax.swing.JButton();
        btGenero = new javax.swing.JButton();
        btCanciones = new javax.swing.JButton();
        btConfi = new javax.swing.JButton();
        btArtista = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);

        btAlbum.setBackground(new java.awt.Color(255, 255, 199));
        btAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/album.png"))); // NOI18N
        btAlbum.setToolTipText("ÁLBUM");
        btAlbum.setBorder(null);
        btAlbum.setBorderPainted(false);
        btAlbum.setContentAreaFilled(false);
        btAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlbum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlbum.setName("Canciones"); // NOI18N
        btAlbum.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/album3.png"))); // NOI18N
        btAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlbumMouseExited(evt);
            }
        });
        btAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlbumActionPerformed(evt);
            }
        });
        add(btAlbum);
        btAlbum.setBounds(110, 70, 70, 67);

        btGenero.setBackground(new java.awt.Color(255, 255, 199));
        btGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/genero.png"))); // NOI18N
        btGenero.setToolTipText("GÉNERO");
        btGenero.setBorder(null);
        btGenero.setBorderPainted(false);
        btGenero.setContentAreaFilled(false);
        btGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGenero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGenero.setName("Canciones"); // NOI18N
        btGenero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/genero3.png"))); // NOI18N
        btGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btGeneroMouseExited(evt);
            }
        });
        btGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeneroActionPerformed(evt);
            }
        });
        add(btGenero);
        btGenero.setBounds(170, 130, 70, 67);

        btCanciones.setBackground(new java.awt.Color(255, 255, 199));
        btCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Canciones.png"))); // NOI18N
        btCanciones.setToolTipText("CANCIONES");
        btCanciones.setBorder(null);
        btCanciones.setBorderPainted(false);
        btCanciones.setContentAreaFilled(false);
        btCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCanciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCanciones.setName("Canciones"); // NOI18N
        btCanciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Canciones3.png"))); // NOI18N
        btCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCancionesMouseExited(evt);
            }
        });
        btCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancionesActionPerformed(evt);
            }
        });
        add(btCanciones);
        btCanciones.setBounds(30, 120, 70, 67);

        btConfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion.png"))); // NOI18N
        btConfi.setToolTipText("CONFIGURACIÓN");
        btConfi.setBorder(null);
        btConfi.setBorderPainted(false);
        btConfi.setContentAreaFilled(false);
        btConfi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConfi.setPreferredSize(new java.awt.Dimension(70, 70));
        btConfi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion3.png"))); // NOI18N
        btConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiActionPerformed(evt);
            }
        });
        add(btConfi);
        btConfi.setBounds(210, 240, 50, 50);

        btArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/artista.png"))); // NOI18N
        btArtista.setToolTipText("ARTISTA");
        btArtista.setBorder(null);
        btArtista.setBorderPainted(false);
        btArtista.setContentAreaFilled(false);
        btArtista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btArtista.setPreferredSize(new java.awt.Dimension(70, 70));
        btArtista.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/artista3.png"))); // NOI18N
        btArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArtistaActionPerformed(evt);
            }
        });
        add(btArtista);
        btArtista.setBounds(100, 200, 65, 65);

        fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo_principal.png"))); // NOI18N
        fondo1.setAlignmentY(0.0F);
        add(fondo1);
        fondo1.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void btAlbumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlbumMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlbumMouseExited
jp_Lista_ALBUM p2;
    private void btAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlbumActionPerformed
        ventana.jp_Principal.getComponent(0).setVisible(false);
       
        if(ventana.jp_Principal.getComponentCount()==3) ventana.jp_Principal.remove(2);
              
          System.out.println("ddd="+ventana.EnRepro);
            p2.setSize(300, 336);
            p2.setLocation(0, 0);
            p2.setVisible(true);
            ventana.jp_Principal.add(p2);
           ventana.jp_Principal.revalidate();
           
        
        
        
    }//GEN-LAST:event_btAlbumActionPerformed

    private void btGeneroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGeneroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btGeneroMouseExited
jp_Lista_GENERO p4;
    private void btGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeneroActionPerformed
         ventana.jp_Principal.getComponent(0).setVisible(false);
       
        if(ventana.jp_Principal.getComponentCount()==3) ventana.jp_Principal.remove(2);
              
           
            p4.setSize(300, 336);
            p4.setLocation(0, 0);
            p4.setVisible(true);
            ventana.jp_Principal.add(p4);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_btGeneroActionPerformed

    private void btCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancionesMouseExited
 public jp_Lista p1 ;
    private void btCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancionesActionPerformed
       
        ventana.jp_Principal.getComponent(0).setVisible(false);
         if(p1==null) p1= new jp_Lista(ventana);
        if(ventana.jp_Principal.getComponentCount()==3) ventana.jp_Principal.remove(2);
              
            
            p1.setSize(300, 336);
            p1.setLocation(0, 0);
            p1.setVisible(true);
            ventana.jp_Principal.add(p1);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_btCancionesActionPerformed
  jp_Configuracion_Total p5 ;
    private void btConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiActionPerformed
         ventana.jp_Principal.getComponent(0).setVisible(false);
         
        if(ventana.jp_Principal.getComponentCount()==3) ventana.jp_Principal.remove(2);
          
            p5.setSize(300, 336);
            p5.setLocation(0, 0);
            p5.setVisible(true);
            ventana.jp_Principal.add(p5);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_btConfiActionPerformed
  jp_Lista_ARTISTA p3 ;
    private void btArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArtistaActionPerformed
         ventana.jp_Principal.getComponent(0).setVisible(false);
      
        if(ventana.jp_Principal.getComponentCount()==3) ventana.jp_Principal.remove(2);
              
           
            p3.setSize(300, 336);
            p3.setLocation(0, 0);
            p3.setVisible(true);
            ventana.jp_Principal.add(p3);
           ventana.jp_Principal.revalidate();
    }//GEN-LAST:event_btArtistaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlbum;
    private javax.swing.JButton btArtista;
    private javax.swing.JButton btCanciones;
    private javax.swing.JButton btConfi;
    private javax.swing.JButton btGenero;
    private javax.swing.JLabel fondo1;
    private javax.swing.JOptionPane mensaje;
    // End of variables declaration//GEN-END:variables
}
