/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

import static java.awt.Frame.ICONIFIED;
import java.awt.Point;

/**
 *
 * @author orlando
 */
public class jp_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form jp_Inicio
     */
    PepperMusic_Frame venta;
    public jp_Inicio(PepperMusic_Frame ventana ) {
        initComponents();
        venta = ventana;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMinimizar = new javax.swing.JButton();
        btAlbum = new javax.swing.JButton();
        btGenero = new javax.swing.JButton();
        btCanciones = new javax.swing.JButton();
        btConfi = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();
        btArtista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/minimizar.png"))); // NOI18N
        btMinimizar.setToolTipText("MINIMIZAR");
        btMinimizar.setBorder(null);
        btMinimizar.setBorderPainted(false);
        btMinimizar.setContentAreaFilled(false);
        btMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMinimizar.setPreferredSize(new java.awt.Dimension(70, 70));
        btMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/minimizar2.png"))); // NOI18N
        btMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinimizarActionPerformed(evt);
            }
        });
        add(btMinimizar);
        btMinimizar.setBounds(160, 20, 60, 58);

        btAlbum.setBackground(new java.awt.Color(255, 255, 199));
        btAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/album.png"))); // NOI18N
        btAlbum.setToolTipText("ÁLBUM");
        btAlbum.setBorder(null);
        btAlbum.setBorderPainted(false);
        btAlbum.setContentAreaFilled(false);
        btAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlbum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlbum.setName("Canciones"); // NOI18N
        btAlbum.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/album3.png"))); // NOI18N
        btAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlbumMouseExited(evt);
            }
        });
        btAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlbumActionPerformed(evt);
            }
        });
        add(btAlbum);
        btAlbum.setBounds(110, 70, 70, 67);

        btGenero.setBackground(new java.awt.Color(255, 255, 199));
        btGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/genero.png"))); // NOI18N
        btGenero.setToolTipText("GÉNERO");
        btGenero.setBorder(null);
        btGenero.setBorderPainted(false);
        btGenero.setContentAreaFilled(false);
        btGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGenero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGenero.setName("Canciones"); // NOI18N
        btGenero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/genero3.png"))); // NOI18N
        btGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btGeneroMouseExited(evt);
            }
        });
        btGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeneroActionPerformed(evt);
            }
        });
        add(btGenero);
        btGenero.setBounds(170, 130, 70, 67);

        btCanciones.setBackground(new java.awt.Color(255, 255, 199));
        btCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Canciones.png"))); // NOI18N
        btCanciones.setToolTipText("CANCIONES");
        btCanciones.setBorder(null);
        btCanciones.setBorderPainted(false);
        btCanciones.setContentAreaFilled(false);
        btCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCanciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCanciones.setName("Canciones"); // NOI18N
        btCanciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Canciones3.png"))); // NOI18N
        btCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCancionesMouseExited(evt);
            }
        });
        btCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancionesActionPerformed(evt);
            }
        });
        add(btCanciones);
        btCanciones.setBounds(30, 120, 70, 67);

        btConfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion.png"))); // NOI18N
        btConfi.setToolTipText("CONFIGURACIÓN");
        btConfi.setBorder(null);
        btConfi.setBorderPainted(false);
        btConfi.setContentAreaFilled(false);
        btConfi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConfi.setPreferredSize(new java.awt.Dimension(70, 70));
        btConfi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/configuracion3.png"))); // NOI18N
        btConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiActionPerformed(evt);
            }
        });
        add(btConfi);
        btConfi.setBounds(210, 220, 65, 65);

        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        btCerrar.setToolTipText("CERRAR");
        btCerrar.setBorder(null);
        btCerrar.setBorderPainted(false);
        btCerrar.setContentAreaFilled(false);
        btCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrar.setPreferredSize(new java.awt.Dimension(70, 70));
        btCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar2.png"))); // NOI18N
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });
        add(btCerrar);
        btCerrar.setBounds(220, 10, 60, 60);

        btArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/artista.png"))); // NOI18N
        btArtista.setToolTipText("ARTISTA");
        btArtista.setBorder(null);
        btArtista.setBorderPainted(false);
        btArtista.setContentAreaFilled(false);
        btArtista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btArtista.setPreferredSize(new java.awt.Dimension(70, 70));
        btArtista.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/artista3.png"))); // NOI18N
        add(btArtista);
        btArtista.setBounds(100, 200, 65, 65);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo_principal.png"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        add(jLabel2);
        jLabel2.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void btMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinimizarActionPerformed
        // TODO add your handling code here:jFrame1.CROSSHAIR_CURSOR
       
       venta.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btMinimizarActionPerformed

    private void btAlbumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlbumMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlbumMouseExited

    private void btAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlbumActionPerformed

    private void btGeneroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGeneroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btGeneroMouseExited

    private void btGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGeneroActionPerformed

    private void btCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancionesMouseExited

    private void btCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancionesActionPerformed
        // TODO add your handling code here:
        //en el constructor de cada jpanel clase debo de poner una variable PepperMusic_Frame a eso declararle una variable global
        
        jp_Canciones p1 = new jp_Canciones(venta);

        p1.setSize(300, 336);
        p1.setLocation(0, 0);
        venta.jp_Principal.removeAll();
        venta.jp_Principal.add(p1);
        venta.jp_Principal.revalidate();
        venta.jp_Principal.repaint();

        //this.dispose();
    }//GEN-LAST:event_btCancionesActionPerformed

    private void btConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiActionPerformed
        // TODO add your handling code here:

        Configuracion form2 = new Configuracion();
        form2.setVisible(true);
        Point p = venta.getLocation();
        form2.setLocation(p.x,p.y);
        venta.dispose();
    }//GEN-LAST:event_btConfiActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
       
        venta.dispose();
    }//GEN-LAST:event_btCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlbum;
    private javax.swing.JButton btArtista;
    private javax.swing.JButton btCanciones;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btConfi;
    private javax.swing.JButton btGenero;
    private javax.swing.JButton btMinimizar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
