/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peppermusic;

import java.awt.event.MouseEvent;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import peppermusic.AutoComboBox.AutocompleteJComboBox;

/**
 *
 * @author orlando
 */
public class jp_Lista_ARTISTA extends jp_Canciones {

    /**
     * Creates new form jp_Lista
     */
    
    jp_Canciones canc;
   
    
    PepperMusic_Frame ventana;
    
    public jp_Lista_ARTISTA(PepperMusic_Frame venta) {
        super(venta);
        ventana=venta;
        initComponents();
        ventana=venta;
       
        if(ventana.EnRepro==false)super.setEnabled_Reproduccion(false);
        super.setSelected_Lista(true);
        super.setSelected_Reproduccion(false);
        
        

       /* jScrollPane2.setViewportView(cancion);

        jp_Album.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 230, 210);
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        pop_tarde = new javax.swing.JMenuItem();
        pop_lista = new javax.swing.JMenu();
        lista_triste = new javax.swing.JMenuItem();
        lista_bailable = new javax.swing.JMenuItem();
        lista_Alegre = new javax.swing.JMenuItem();
        lista_Estudio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        pop_letras = new javax.swing.JMenuItem();
        pop_Eliminar = new javax.swing.JMenuItem();
        btnActualizarCanciones = new javax.swing.JButton();
        jb_buscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jcm_buscar = new AutocompleteJComboBox(ventana.searchable);
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_Album = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_canciones = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_tarde = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        popup.setComponentPopupMenu(popup);
        popup.setInvoker(lst_canciones);

        pop_tarde.setText("Agregar a Escuchar más tarde");
        pop_tarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_tardeActionPerformed(evt);
            }
        });
        popup.add(pop_tarde);

        pop_lista.setText("Agregar a Lista de Reproducción");

        lista_triste.setText("Triste");
        pop_lista.add(lista_triste);

        lista_bailable.setText("Bailable");
        pop_lista.add(lista_bailable);

        lista_Alegre.setText("Alegre");
        pop_lista.add(lista_Alegre);

        lista_Estudio.setText("Estudio");
        pop_lista.add(lista_Estudio);

        popup.add(pop_lista);
        popup.add(jSeparator1);

        pop_letras.setText("AGREGAR LETRAS");
        popup.add(pop_letras);

        pop_Eliminar.setText("ELIMINAR");
        popup.add(pop_Eliminar);

        setOpaque(false);
        setLayout(null);

        btnActualizarCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_actualizar.png"))); // NOI18N
        btnActualizarCanciones.setBorderPainted(false);
        btnActualizarCanciones.setContentAreaFilled(false);
        btnActualizarCanciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_actualizar2.png"))); // NOI18N
        btnActualizarCanciones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_actualizar2.png"))); // NOI18N
        btnActualizarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCancionesActionPerformed(evt);
            }
        });
        add(btnActualizarCanciones);
        btnActualizarCanciones.setBounds(245, 55, 30, 30);

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Boton 9.png"))); // NOI18N
        jb_buscar.setToolTipText("Buscar");
        jb_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });
        add(jb_buscar);
        jb_buscar.setBounds(230, 30, 27, 25);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/album_retroceder.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(140, 65, 30, 21);

        jcm_buscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcm_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcm_buscarMouseClicked(evt);
            }
        });
        jcm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcm_buscarActionPerformed(evt);
            }
        });
        add(jcm_buscar);
        jcm_buscar.setBounds(38, 30, 190, 25);

        jp_Album.setAlignmentX(0.0F);
        jp_Album.setAlignmentY(0.0F);
        jp_Album.setOpaque(false);
        jp_Album.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 102, 102));

        lst_canciones.setBackground(new java.awt.Color(0, 0, 0));
        lst_canciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lst_canciones.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        lst_canciones.setForeground(new java.awt.Color(255, 255, 255));
        lst_canciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_canciones.setToolTipText("");
        lst_canciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_cancionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lst_canciones);

        jp_Album.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 230, 210);

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Recursos/artista_cancion.png")), jp_Album, "Todas las Canciones"); // NOI18N

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jScrollPane4.setBackground(new java.awt.Color(255, 102, 102));
        jScrollPane4.setAlignmentX(0.0F);
        jScrollPane4.setAlignmentY(0.0F);

        lst_tarde.setBackground(new java.awt.Color(0, 0, 0));
        lst_tarde.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lst_tarde.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        lst_tarde.setForeground(new java.awt.Color(255, 255, 255));
        lst_tarde.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_tarde.setToolTipText("");
        lst_tarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_tardeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lst_tarde);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(0, 0, 230, 210);

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton_mastarde.png")), jPanel3, "Escuchar más tarde"); // NOI18N

        add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 60, 240, 240);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_Celeste.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 300, 336);
    }// </editor-fold>//GEN-END:initComponents
DefaultListModel modelo = new DefaultListModel();
    private void pop_tardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_tardeActionPerformed
        // TODO add your handling code here:
        /*
        
        
            if( jScrollPane2.getViewport().getComponent(0)==cancion) modelo.addElement((String)cancion.getSelectedValue());
         else  modelo.addElement((String)lst_canciones.getSelectedValue());
           lst_tarde.setModel(modelo);*/
        
        
    }//GEN-LAST:event_pop_tardeActionPerformed

    private void lst_tardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_tardeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lst_tardeMouseClicked

    private void lst_cancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_cancionesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2&&lst_canciones.getSelectedValue()!=null) {

             
        DefaultListModel model_artista = new DefaultListModel();
         if( jScrollPane2.getViewport().getComponent(0)==lst_canciones){
              JList lista = new JList();
           lista.setBackground(new java.awt.Color(0, 0, 0));
        lista.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lista.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
       lista.setForeground(new java.awt.Color(255, 255, 255));
        
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setToolTipText("");
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventana.indice_cancion = lista.locationToIndex(evt.getPoint());
                lst_cancionesMouseClicked(evt);
                
            }
        }); 
              ventana.indice_album = lst_canciones.locationToIndex(evt.getPoint());
            Iterator prueba = ventana.Lista_artista.get(ventana.indice_album).items_artista().iterator();
         
        while (prueba.hasNext()) {
             ListaDeReproduccion elemento=( ListaDeReproduccion)prueba.next();
             model_artista.addElement(elemento.nom_cancion);
             
            System.out.println(elemento.nom_cancion);
            //System.out.println(elemento.nom_cancion+" "+elemento.nom_artista+" "+elemento.nom_album);    
        }
             
        lista.setModel(model_artista );
          jScrollPane2.setViewportView(lista);
          jp_Album.add(jScrollPane2);
          jScrollPane2.setBounds(0, 0, 230, 210);
        
       
         
         }else{
             
             
                 
                 ventana.jp_Principal.getComponent(2).setVisible(false);
                 ventana.NoRepro = false;
                 super.setEnabled_Reproduccion(true);
                 ventana.jp_Principal.getComponent(1).setVisible(true);
                 
                 
                 try {
                     ventana.EnRepro=true;
                     
                    ventana.mi_reproductor.play(ventana.Lista_artista.get(ventana.indice_album).items_artista().get(ventana.indice_cancion).ruta);
                     
                     
                 } catch (Exception ex) {
                     System.out.println("Error: " + ex.getMessage());
                 }
                 
        }
        }
        if(evt.getButton()==MouseEvent.BUTTON3){
            boolean isPopUp = evt.isPopupTrigger();
/*
            if ( !isPopUp) {

                int index= cancion.locationToIndex(evt.getPoint());

                if (index !=-1){
                    lst_canciones.setSelectedIndex(cancion.locationToIndex(evt.getPoint()));
                    //Todo esto de debajo se puede poner en otro método si se quiere
                    //Tienes que borrar antes los elementos que hubiese en el popup

                    //Añades, por ejemplo, el nombre del elemento seleccionado como elemento del popup
                    // popup.add((String)lst_canciones.getSelectedValue());
                    // popup.add("Agregar a Lista de reproducción");

                    popup.setLocation(evt.getLocationOnScreen());

                    popup.setVisible(true);
                }
            }*/
        }
    }//GEN-LAST:event_lst_cancionesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jScrollPane2.setViewportView(lst_canciones);
        jp_Album.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 230, 210);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnActualizarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCancionesActionPerformed

        if(!ventana.inicial.buscando)ventana.inicial.start();
    }//GEN-LAST:event_btnActualizarCancionesActionPerformed
public String buscarRuta(String busca){
                
        Iterator itListaempleado= ventana.lista_completa.iterator();
        
         
        
        while (itListaempleado.hasNext()) {
            ListaDeReproduccion elemento=(ListaDeReproduccion)itListaempleado.next();
            if(elemento.nom_cancion.equals(busca)){
                  ventana.nom_cancion=elemento.nom_cancion;
                return elemento.ruta;
          
            }
            //System.out.println(elemento.nom_cancion+" "+elemento.nom_artista+" "+elemento.nom_album);    
        }
        return "NO EXISTE";
 }
    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:

        if(jcm_buscar.getSelectedItem()!=null){

            String ruta = buscarRuta(jcm_buscar.getSelectedItem().toString());
            if(!ruta.equals("NO EXISTE")){

                ventana.jp_Principal.getComponent(2).setVisible(false);
                ventana.NoRepro = false;
                // ventana.cancion_actual= ventana.lista_completa.get(index);
                //   ventana.ruta_txt = "C:\\PepperMusic_Datos\\Letras\\"+ventana.lista_completa.get(ventana.indice).nom_cancion+".txt";
                // ventana.nom_cancion=lst_tarde.getSelectedValue().toString();
                super.setEnabled_Reproduccion(true);
                ventana.jp_Principal.getComponent(1).setVisible(true);

                try {
                    ventana.EnRepro=true;//"/Recursos/You're_My_Best_Friend.mp3"

                    ventana.mi_reproductor.play(ruta);

                } catch (Exception ex) {
                    System.out.println("Error men: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jcm_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcm_buscarMouseClicked
        // TODO add your handling code here:
        //  if(evt.getClickCount()==1){
            System.out.println(jcm_buscar.getSelectedItem());
            //}
    }//GEN-LAST:event_jcm_buscarMouseClicked

    private void jcm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcm_buscarActionPerformed
        // TODO add your handling code here:
        //     System.out.println(jcm_buscar.getSelectedItem());
    }//GEN-LAST:event_jcm_buscarActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCanciones;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_buscar;
    public AutocompleteJComboBox jcm_buscar;
    private javax.swing.JPanel jp_Album;
    private javax.swing.JMenuItem lista_Alegre;
    private javax.swing.JMenuItem lista_Estudio;
    private javax.swing.JMenuItem lista_bailable;
    private javax.swing.JMenuItem lista_triste;
    public javax.swing.JList<String> lst_canciones;
    public javax.swing.JList<String> lst_tarde;
    private javax.swing.JMenuItem pop_Eliminar;
    private javax.swing.JMenuItem pop_letras;
    private javax.swing.JMenu pop_lista;
    private javax.swing.JMenuItem pop_tarde;
    private javax.swing.JPopupMenu popup;
    // End of variables declaration//GEN-END:variables
}
